---
name: Checks

on: [push]

jobs:
  test-and-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Tests
        run: docker run --rm my-app sh -c "python manage.py wait_for_db && python manage.py test"

      - name: Run Lint
        run: docker run --rm my-app sh -c "black . && flake8"
