---
name: Checks

on: [push]

jobs:
  login:
    name: Login to Docker Hub
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  test:
    name: Test
    runs-on: ubuntu-20.04
    needs: login
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Tests
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    needs: login
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Lint
        run: docker compose run --rm app sh -c "flake8"